site_name: Object Renamer
nav:
  - Home: index.md
  - Object Renamer: 
    - Overview: object_renamer.md
    - UI: obre_UI.md
    - Renamer: obre_op_renamer.md
  - Test: test.md
  - About: about.md
theme: readthedocs

