markdown_extensions:
  - sane_lists
  - md_in_html
  - attr_list
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.copy
    - search.highlight
    - header.autohide

site_name: To Automate
nav:
  - ToAutomate: 
    - Overview: index.md
    - User Interface: TAMT_UI.md
    - Preferences: TAMT_preferences.md
    - Object & Scene Tools: TAMT_op_3DTools.md
    # - Mesh Tools: TAMT_op_MeshTools.md
    # - UV Tools: TAMT_op_UVTools.md
    # - Export Tools: TAMT_op_EXPTools.md
  - About: about.md

  
 

