site_name: Object Renamer
nav:
  - Home: index.md
  - Object Renamer: 
    - Overview: object_renamer.md
    - UI: obre_UI.md
    - Rename Tool: obre_op_renamer.md
    - Collection Organizer: obre_op_colOrganize.md
    - Miscellaneous Tools: obre_op_misc.md
  - Test: test.md
  - About: about.md
theme: readthedocs

